name: Deploy to DreamHost (Rsync over SSH with password, changed files only)

on:
  push:
    branches: [ main ]        # deploy automatically after merge to main
  workflow_dispatch:          # allow manual "Run workflow"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2      # enough history for diffs

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy changed files via rsync over SSH (password auth)
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}            
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}    
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}    
          SFTP_SERVER_DIR: ${{ secrets.SFTP_SERVER_DIR }}
        run: |
          echo "Starting rsync deployment to $SFTP_HOST ..."
          # Use sshpass to provide password to ssh/rsync non-interactively
          sshpass -p "$SFTP_PASSWORD" rsync -az --delete \
            --checksum \
            --omit-dir-times \
            --no-perms --no-owner --no-group \
            --modify-window=2 \
            --info=stats2,progress2 \
            --exclude=".git*" \
            --exclude=".github" \
            --exclude="docker" \
            --exclude="tests" \
            --exclude="node_modules" \
            --exclude="vendor" \
            --exclude="*.md" \
            --exclude="*.yml" \
            --exclude="*.yaml" \
            --exclude=".env*" \
            --exclude="sql" \
            --exclude=".vscode" \
            --exclude=".idea" \
            --exclude="*.map" \
            --exclude="composer.*" \
            -e "ssh -p 22 -o StrictHostKeyChecking=no" \
            ./  "$SFTP_USERNAME@$SFTP_HOST:$SFTP_SERVER_DIR"

          echo "✅ Rsync deployment completed."

      - name: Show deployment summary
        if: success()
        run: |
          echo "Deployment finished at $(date -u) UTC"
          echo "Target: ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_SERVER_DIR }}"
