name: Deploy to DreamHost (SFTP, changed files)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy via SFTP (DreamHost - SSH key)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './'
          remote_path: ${{ secrets.SFTP_SERVER_DIR }}
          # rsync-like exclusions
          args: >
            -avzr --delete
            --exclude=".git*" --exclude=".github"
            --exclude="docker" --exclude="tests"
            --exclude="node_modules" --exclude="vendor"
            --exclude="*.md" --exclude="*.yml" --exclude="*.yaml"
            --exclude=".env*" --exclude="sql"
            --exclude=".vscode" --exclude=".idea"
            --exclude="*.map" --exclude="composer.*"
